name: Deploy Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build-new-version:
        description: 'Build now and deploy the app'
        default: 'true'
        required: false


jobs:
  deploy-web-app:
    uses: Practica-Supervisada-UCR-2025/Repo-DevOps/.github/workflows/deploy-app-reusable-workflow.yml@main
    with:
      app_path: "./ucrconnect-dashboard"
      image_name: "frontend-app"
      container_name: "frontend-app"
      production_server_port: "3001"
      program_assigned_port: "3000"
      env_directory: "frontend-app"

    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DEPLOYMENT_SERVER_HOST: ${{ secrets.DEPLOYMENT_SERVER_HOST }}
      FIREBASE_ENV_FILE: ${{ secrets.FIREBASE_ENV_FILE }}
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
